version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - jmartinezhern
  ignore:
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
