  linters-settings:
    govet:
      check-shadowing: true
    golint:
      min-confidence: 0
    gocyclo:
      min-complexity: 10
    maligned:
      suggest-new: true
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental

  linters:
    enable-all: true
    disable:
      - maligned
      - prealloc
      - gochecknoglobals

  issues:
    exclude-rules:
      - text: "weak cryptographic primitive"
        linters:
          - gosec

