#[sync]
#time="15:20"
#interval="15"

#[service]
#enable_plugins = true
#enable_admin_socket = true

#[[plugins]]
#name = "evernote"
#binary_path= ".config/lib"
#custom_config_pair = "key-id"

plugins = [ "/home/varddum/workspace/projects/syndication/src/github.com/varddum/syndication/api.so" ]

[admin]
enable = true
socket_path = "/tmp/syndication.socket"

[server]
auth_secret = "secret"
#auth_secret_file_path="$HOME/.config/syndication/secret"
http_port = 8080
tls_port = 443
enable_http_requests_log = true
enable_panic_print_stack = true
enable_tls = false

[sync]
interval= "5m"

[database]
  [database.sqlite]
  enable = true
  connection ="/tmp/syndication.db"

  #[database.postgres]
  #enable = false
  #connection = "user=synd dbname=syndication sslmode=disable"

  #[database.mysql]
  #enable = false
  #connection = "synd:test@/syndication?parseTime=True"

